export { account, session, user, verification } from "./auth.js";
export {
  agentRuns,
  campaigns,
  contacts,
  contactVerifications,
  evidence,
  founders,
  gmailCredentials,
  gmailOauthStates,
  leads,
  leadScores,
  leadStatusHistory,
  messageApprovals,
  messageDrafts,
  outboundMessages,
  outboxEvents,
  organizations,
  sourceDocuments,
  sources,
  strategyBriefs,
  sendAttempts,
  senders,
  sequences,
  suppressionList
} from "./crm.js";
export {
  auditLog,
  featureFlags,
  killSwitches,
  regions,
  schemaMigrations,
  systemSettings
} from "./foundations.js";

import { account, session, user, verification } from "./auth.js";
import {
  agentRuns,
  campaigns,
  contacts,
  contactVerifications,
  evidence,
  founders,
  gmailCredentials,
  gmailOauthStates,
  leads,
  leadScores,
  leadStatusHistory,
  messageApprovals,
  messageDrafts,
  outboundMessages,
  outboxEvents,
  organizations,
  sourceDocuments,
  sources,
  strategyBriefs,
  sendAttempts,
  senders,
  sequences,
  suppressionList
} from "./crm.js";
import {
  auditLog,
  featureFlags,
  killSwitches,
  regions,
  schemaMigrations,
  systemSettings
} from "./foundations.js";

export const schema = {
  account,
  agentRuns,
  auditLog,
  campaigns,
  contacts,
  contactVerifications,
  evidence,
  featureFlags,
  founders,
  gmailCredentials,
  gmailOauthStates,
  killSwitches,
  leads,
  leadScores,
  leadStatusHistory,
  messageApprovals,
  messageDrafts,
  outboundMessages,
  outboxEvents,
  organizations,
  regions,
  schemaMigrations,
  session,
  sourceDocuments,
  sources,
  strategyBriefs,
  sendAttempts,
  senders,
  sequences,
  suppressionList,
  systemSettings,
  user,
  verification
};
